version: '3.8'

services:

  artillery-online-nginx:
    image: nginx:1.23-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
    networks:
      artillery-online-net:

  artillery-online-postgres:
    image: postgres:16.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: artillery
      POSTGRES_USER: artillery
      POSTGRES_DB: artillery
    networks:
      artillery-online-net:

networks:
  artillery-online-net:
